version: '3'
services:
  app: { build: ., ports: [ "8080:8080" ], environment: [ SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/librare, SPRING_DATASOURCE_USERNAME=postgres, SPRING_DATASOURCE_PASSWORD=librare2024 ], depends_on: [ db ] }
  db: { image: postgres:13, volumes: [ ./data:/data ], environment: [ POSTGRES_USER=postgres, POSTGRES_PASSWORD=librare2024, POSTGRES_DB=librare ], ports: [ "5432:5432" ] }
