version: '3'
services:
  app: { build: ., ports: [ "8080:8080" ], environment: [ SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/librare, SPRING_DATASOURCE_USERNAME=postgres, SPRING_DATASOURCE_PASSWORD=librare2024, SPRING_REDIS_HOST=redis ], depends_on: [ db, redis ] }
  db: { image: postgres:13, volumes: [ ./data:/data ], environment: [ POSTGRES_USER=postgres, POSTGRES_PASSWORD=librare2024, POSTGRES_DB=librare ], ports: [ "5432:5432" ] }
  redis: { image: redis:latest, ports: [ "6379:6379" ] }
